# Usar a imagem do SDK .NET 8.0
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copie os arquivos do projeto
COPY . .

# Restaure as dependências
RUN dotnet restore "ICorteApi/ICorteApi.csproj"

# Compile o projeto
RUN dotnet publish "ICorteApi/ICorteApi.csproj" -c Release -o out

# Fase de runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/out ./

# Comando para iniciar a aplicação
ENTRYPOINT ["dotnet", "ICorteApi.dll"]
